pekko {
  actor {
    provider = "local"
    allow-java-serialization = on
    warn-about-java-serializer-usage = off
  }

  loglevel = "INFO"

  persistence {
    journal.plugin = "jdbc-journal"
    snapshot-store.plugin = "pekko.persistence.snapshot-store.local"
  }
}

jdbc-journal {
  slick {
    profile = "slick.jdbc.PostgresProfile$"
    db {
      host = "localhost"
      host = ${?POSTGRES_HOST}
      port = "5432"
      port = ${?POSTGRES_PORT}
      database = "aviation"
      database = ${?POSTGRES_DB}
      url = "jdbc:postgresql://"${jdbc-journal.slick.db.host}":"${jdbc-journal.slick.db.port}"/"${jdbc-journal.slick.db.database}
      user = "aviation"
      user = ${?POSTGRES_USER}
      password = "aviation"
      password = ${?POSTGRES_PASSWORD}
      driver = "org.postgresql.Driver"
      numThreads = 5
      maxConnections = 5
      queueSize = 100
    }
  }
}

kafka {
  bootstrap-servers = "localhost:9092"
  bootstrap-servers = ${?KAFKA_BOOTSTRAP_SERVERS}
  topic = "aircraft.state.vectors"
  topic = ${?KAFKA_TOPIC}
}
